#include "Lua/lua.bi"

#include "IUP/iup.bi"

#include "IUP/iuplua.bi"
#include "IUP/iupluacontrols.bi"
#include "IUP/iupluagl.bi"
#include "IUP/iupluaglcontrols.bi"
#include "IUP/iupluaim.bi"
#include "IUP/iupluamatrixex.bi"
#include "IUP/iuplua_mglplot.bi"
#include "IUP/iupluaole.bi"
#include "IUP/iuplua_plot.bi"
#include "IUP/iuplua_pplot.bi"
#include "IUP/iuplua_scintilla.bi"
#include "IUP/iupluatuio.bi"
#include "IUP/iupluaweb.bi"
